### PR TITLE
feat: add possibility to clear all sshKeys from config

### PR DESCRIPTION
**Pull request by aTEraGOU**

### CODE REVIEW

**Comment by aTEraGOU** [comment]
@alexgg @jaomaloy Please review this small change.

**Comment by alexgg** [comment]
thanks @aTEraGOU looks good

**Comment by alexgg** [comment]
Pending on https://github.com/balena-os/configizer/pull/20

**Comment by alexgg** [comment]
@aTEraGOU could you please add a footer with a `Change-type: patch`? It's needed for CI checks to pass. Thanks.

**Comment by aTEraGOU** [comment]
@alexgg should be ok now?

**Pull request merged**
